### ISSUE TITLE
Exclamation mark handler has weird parsing semantics

### ISSUE THREAD

**Issue by hmenke** [cgnieder/chemformula#14]
**Description**

The formula argument in the exclamation mark handler seems to be very sensitive to surrounding space.  In the `Huh?` case in the MWE it only renders strangely, but in the `Boom!` case it crashes with `! Missing $ inserted.`

**MWE**

```latex
\documentclass{article}
\usepackage{chemformula}
\begin{document}
Okay. \ch{!(yellow)( HIn_{(aq)} )}

Huh? \ch{!(yellow)(HIn_{(aq)})}

Okay. \ch{!(yellow)( HIn^+_{(aq)} )}

Boom! \ch{!(yellow)(HIn^+_{(aq)})}
\end{document}
```

**Version information**

```
chemformula.sty    2020/02/01 v4.15i typeset chemical compounds and reactions (
CN)
```

**Comment by cgnieder** [comment]
Maybe I should make the importance of surrounding spaces more clear in the manual but it actually *is* mentioned (section 4 of the current manual). The examples for the `!()()` also all show the surrounding spaces.

The messages are of course misleading but cases 2 and 4 are actually expected to break.

The different outcome of 2 and 4 is due to the fact that `_` still has catcode letter which you can see if you add `\usepackage[T1]{fontenc}`. Arguably it should have it's usual catcode again here…

**Comment by hmenke** [comment]
Not entirely consistent then.
https://github.com/cgnieder/chemformula/blob/cd3bae92dbc01fe5e4094d592896b08610d50f91/chemformula-manual.tex#L1225
But yes, not a bug.

**Comment by cgnieder** [comment]
>  \ch{!(water)(H2O)}

That is actually an example for what is happening when you don't leave spaces:

![image](https://user-images.githubusercontent.com/2248538/78472396-959a1b00-7738-11ea-8e33-7de38eb76c5a.png)
